Use NSFileCoordinator to listen see if the repository is deleted or moved
gitx/gitx pull request #90
Opened 2017-04-27 16:14 UTC by ksuther

This will detect if a repository gets deleted or moved and will close the document instead of trying to read from the old path and potentially crashing.

For the future:
It would be even better to automatically update the repository to the new location, but the current architecture makes that a bit messy. If the nested NSDocument classes get cleaned up we could reallocate the GTRepository and reuse the document.

2017-07-04 21:26 UTC, tiennou commented
That's nice. Just to be clear, the plan is to keep splitting `PBGitRepository` from `PBGitRepositoryDocument` and make the former a non-`NSDocument` subclass.

2018-03-14 21:21 UTC, tiennou commented
I'd be interested to know if your future point could be done now, since `master` no longer has PBGitRepository as a document object ?

2021-01-28 06:29 UTC, hannesa2 commented
It would be nice, when you rebase to recent master to have a CI build. Thank you !

2021-04-25 17:46 UTC, ksuther commented
Rebased on top of master.

2021-04-26 03:36 UTC, jspiro requested changes
It seems that even with the re-base GitHub actions is not running. Could you try to get it to run on this build? I'm not sure why rebasing didn't work.￼

2021-04-26 03:48 UTC, jspiro approved these changes

2021-04-26 04:46 UTC, hannesa2 commented
> It seems that even with the re-base GitHub actions is not running

Hmm, I see it working. Did someone something special, or was it just running with a delay ?

2021-04-26 04:46 UTC, merged

2021-04-26 04:51 UTC, hannesa2 commented
Ok, I see this new feature

<img width="541" alt="image" src="https://user-images.githubusercontent.com/3314607/116030273-792a9280-a65b-11eb-9cb7-defa775ffa98.png">

https://docs.github.com/en/actions/managing-workflow-runs/approving-workflow-runs-from-public-forks

2021-04-26 04:52 UTC, jspiro commented
Yeah I fixed it. I don't know why it doesn't show that on the mobile app. I also can't see a way to disable it, I checked. Thanks for the contribution!